<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Test Project</title>
        <?php echo $this->headLink()->appendStylesheet('/Test/public/css/global.css') ?>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <h1>Zend Framework Testing</h1>
                <h2>I have no idea what I'm doing!</h2>
            </div>

            <div id="navigation">

            </div>

            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>

            <div id="footer">
                <p>Web Template by <a href="http://andreasviklund.com">Andreas Viklund</a></p>
            </div>
        </div>
    </body>
</html>